require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'RNMobileApp' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :engine => :hermes,
    :hermes_enabled => true
  )

  target 'RNMobileAppTests' do
    inherit! :complete
    post_install do |installer|
      react_native_post_install(
        installer,
        config[:reactNativePath],
        :mac_deployment_target => '10.15'
      )
    end
  end
end

post_install do |installer|
  react_native_post_install(
    installer,
    config[:reactNativePath],
    :mac_deployment_target => '10.15'
  )
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
end